# Generated by Django 2.2 on 2019-04-06 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Announcment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='Sport', max_length=100, verbose_name='Sport')),
                ('location', models.CharField(default='Location', max_length=100, verbose_name='Location')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('wanted_people', models.IntegerField()),
                ('registered_people', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('skill_level', models.CharField(default='Average', max_length=100, verbose_name='Level of skills')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
