# Generated by Django 2.2 on 2019-04-06 09:23

from django.db import migrations, models
import game_announcement.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_announcement', '0001_initial'),
    ]

    operations = [
    ]
