# Generated by Django 2.2 on 2019-04-06 09:23

from django.db import migrations, models
import game_announcement.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_announcment',
            name='skill_level',
            field=models.CharField(choices=[(game_announcement.models.Sports('Football'), 'Football'), (game_announcement.models.Sports('Basketball'), 'Basketball'), (game_announcement.models.Sports('Volleyball'), 'Volleyball')], max_length=100, verbose_name='Level of skills'),
        ),
        migrations.AlterField(
            model_name='game_announcment',
            name='sport',
            field=models.CharField(choices=[(game_announcement.models.Sports('Football'), 'Football'), (game_announcement.models.Sports('Basketball'), 'Basketball'), (game_announcement.models.Sports('Volleyball'), 'Volleyball')], max_length=100, verbose_name='Sport'),
        ),
    ]
