# Generated by Django 2.2 on 2019-04-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_announcement', '0003_auto_20190406_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Announcment',
            new_name='Game_Announcement',
        ),
    ]
