# Generated by Django 2.2 on 2019-04-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_announcement', '0009_game_announcement_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_announcement',
            name='joined',
            field=models.CharField(default=';', max_length=10000),
        ),
    ]
