# Generated by Django 2.2 on 2019-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_announcement', '0010_auto_20190406_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_announcement',
            name='registered_people',
            field=models.IntegerField(default=0),
        ),
    ]
